name: Publisher - Notifier

on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  notify-connector:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204)
    runs-on: ubuntu-latest
    steps:
    - name: Notify backend endpoint
      run: |
        sleep 1s
        PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
        WEBSITE_NAME="${{ vars.WEBSITE_NAME }}"
        URI=$(echo "${{ vars.CONNECTOR_DOMAIN }}/$WEBSITE_NAME")
        BODY='{ "paths": [ "'$PAGE_PATH'" ] }'
        BODY="$(echo "$BODY" | jq -c)"
        response=$(curl -s -X POST "https://0wirer4081.execute-api.us-east-1.amazonaws.com/betapreview" -d "test body")
        echo "response: $response"
        echo "auth_key: ${{ secrets.API_KEY }}"
        echo "cme_endpoint: ${{ vars.CME_ENDPOINT }}"
    - name: Mostrar todas las variables
      run: env | sort
      shell: bash
