name: Publisher - Notifier

on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  notify-connector:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204)
    runs-on: ubuntu-latest
    steps:
    - name: Notify backend endpoint
      env:
          MI_SECRET: ${{ secrets.AUTH_KEY }}
      run: |
        sleep 1s
        PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
        WEBSITE_NAME="${{ vars.WEBSITE_NAME }}"
        CME_ENDPOINT="${{ vars.CME_ENDPOINT }}"
        URI=$(echo "${{ vars.CONNECTOR_DOMAIN }}/$WEBSITE_NAME")
        BODY='{ "paths": [ "'$PAGE_PATH'" ] }'
        BODY="$(echo "$BODY" | jq -c)"
        response=$(curl 'https://apitest.newsan.com.ar/api/products/stock/ebs/reserve?sku=9132LM620PI' -H 'auth-key: 028450faa154a7df0a69f15387b8a4f5')
        echo "response: $BODY auth_key: ${{ secrets.AUTH_KEY }} cme_endpoint: $CME_ENDPOINT"
        echo "cme_endpoint: $MI_SECRET"
      shell: bash
